# @AUTHOR: imyme6yo "imyme6yo@gmail.com"
# @DRAFT: 20210424
# @UPDATE: 20210521
# Arguments
ARG PYTHON=3.8
ARG ALPINE=3.10
ARG TAG=python${PYTHON}-alpine${ALPINE}

# Base image
FROM tiangolo/uvicorn-gunicorn-fastapi:${TAG}

# Labels
# Maintainer
LABEL maintainer="imyme6yo"
LABEL email="imyme6yo@gmail.com"
# Service
LABEL project=myproj
LABEL name=myproj-myapp
LABEL version=0.1.1

ARG MODE=DEV
ARG DEBUG='true'
ARG IP_MAIN=127.0.0.1
ARG IP_DEV=localhost
ARG PROJECT=myproj
ARG PROJECT_NETWORK=${PROJECT}-network
ARG IMAGE_TAG=dev
ARG SERVICE=myapp
ARG SERVICE_PORT=10111
ARG SERVICE_CONTAINER_PORT=3000
ARG DATABASE_HOST=${PROJECT}-${SERVICE}-db
ARG DATABASE_PORT=5432
ARG DATABASE_USER=admin
ARG DATABASE_PASSWORD=password
ARG DATABASE_DB=myapp

# Envs
ENV MODE=${MODE}
ENV DEBUG=${DEBUG}
ENV IP_MAIN=${IP_MAIN}
ENV IP_DEV=${IP_DEV}
ENV PROJECT=${PROJECT}
ENV IMAGE_TAG=${IMAGE_TAG}
ENV SERVICE=${SERVICE}
ENV SERVICE_PORT=${SERVICE_PORT}
ENV SERVICE_CONTAINER_PORT=${SERVICE_CONTAINER_PORT}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_USER=${DATABASE_USER}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_DB=${DATABASE_DB}

COPY ${SERVICE} /opt/${PROJECT}/${SERVICE}
COPY run.sh /opt/${PROJECT}/
WORKDIR /opt/${PROJECT}
CMD ["ash"]