# @AUTHOR: imyme6yo "imyme6yo@gmail.com"
# @DRAFT: 20200801
---
    - name: create vue3 project, myapp
      hosts: 127.0.0.1
      tasks:
        - name: create network
          docker_network: 
            state: present
            name: $PROJECT_NETWORK
            attachable: yes
        - name: create docker image, myapp-web:dev
          docker_image:
            name: "$PROJECT-$SERVICE"
            tag: $IMAGE_TAG
            build:
              path: .
              dockerfile: Dockerfile.start
              args:
                DEFUG: $DEBUG
                DIR: $WEB_DIR
                PROJECT: $PROJECT
                IMAGE_TAG: $IMAGE_TAG