# @AUTHOR: imyme6yo "imyme6yo@gmail.com"
# @DRAFT: 20200803
# @UPDATE: 20200804
# Arguments
ARG NODE=14.7.0
ARG ALPINE=3.10
ARG TAG=${NODE}-alpine${ALPINE}

# Base image
FROM node:${TAG}

# Labels
# Maintainer
LABEL maintainer="imyme6yo"
LABEL email="imyme6yo@gmail.com"
# Service
LABEL Name=myproject-web
LABEL Version=0.0.1

# Arguments
ARG DEBUG=true
ARG PROJECT=myproject
ARG SERVICE=web
ARG IMAGE_TAG=dev
ARG HOST=${PROJECT}-${SERVICE}
ARG PORT=3000

# Envs
ENV DEBUG=${DEBUG}
ENV HOST=${HOST}
ENV PORT=${PORT}
ENV PROJECT=${PROJECT}
ENV SERVICE=${SERVICE}
ENV CONTAINER=${PROJECT}-${SERVICE}
ENV IMAGE_TAG=${IMAGE_TAG}

# Install Alpine packages
RUN apk update && apk upgrade
RUN apk add --no-cache  git

# Install node dependencies
RUN npm install -g http-server

RUN mkdir ${DIR}
WORKDIR ${DIR}
COPY . .