# @AUTHOR: imyme6yo "imyme6yo@gmail.com"
# @DRAFT: 20200801
# @UPDATE: 20200810
---
  - name: create svelte project, myapp
    hosts: 127.0.0.1
    tasks:
      - name: remove docker container, myproject-web
        docker_container:
          name: "{{ lookup('env', 'PROJECT') }}-{{ lookup('env', 'WEB_SERVICE') }}"
          state: absent
      - name: remove docker image, myproject-web:dev
        docker_image:
          state: absent
          name: "{{ lookup('env', 'PROJECT') }}-{{ lookup('env', 'WEB_SERVICE') }}"
          tag: "{{ lookup('env', 'IMAGE_TAG') }}"
      - name: create docker image, myproject-web:dev
        docker_image:
          state: present
          name: "{{ lookup('env', 'PROJECT') }}-{{ lookup('env', 'WEB_SERVICE') }}"
          tag: "{{ lookup('env', 'IMAGE_TAG') }}"
          build:
            path: .
            dockerfile: Dockerfile.start
            args:
              DEFUG: "{{ lookup('env', 'DEBUG') }}"
              PROJECT: "{{ lookup('env', 'PROJECT') }}"
              SERVICE: "{{ lookup('env', 'WEB_SERVICE') }}"
              IMAGE_TAG: "{{ lookup('env', 'IMAGE_TAG') }}"
          source: build
      - name: run docker container, myproject-web
        docker_container:
          name: "{{ lookup('env', 'PROJECT') }}-{{ lookup('env', 'WEB_SERVICE') }}"
          state: started
          recreate: yes
          # auto_remove: yes
          image: "{{ lookup('env', 'PROJECT') }}-{{ lookup('env', 'WEB_SERVICE') }}:{{ lookup('env', 'IMAGE_TAG') }}"
          volumes:
            - "{{ lookup('env', 'CONTEXT') }}/{{ lookup('env', 'WEB_SERVICE') }}:/{{ lookup('env', 'WEB_SERVICE') }}"
          command: "sh /{{ lookup('env', 'WEB_SERVICE') }}/startup.sh"
          # detach: yes
          # interactive: yes
          # command: ash